homework sprint 3
vladis62/yandex-asoftware-architect pull request #5
Opened 2024-11-17 17:07 UTC by vladis62

2024-11-20 19:40 UTC, dchekushin requested changes

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/README.md
> +
Укажите технологии (язык программирования, СУБД и т.д.) используемые в монолите.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/README.md
> +
Сложность развертывания монолита ?

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/README.md
> +
Опишите домены предметной области

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/context/SmartHomeMonolit_Context.puml
> +Person(user, "User", "Владелец системы умного дома")
Стоит выделить мобильное приложение и веб-сайт отдельным контейнером. Пользователь использует веб-сайт, который в свою очередь Smart Home Monolith

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/context/SmartHomeMonolit_Context.puml
> +title SmartHome Context Diagram
На схеме укажите:

- Технологи используемые в монолите.
- Протоколы взаимодействия (HTTP / Драйвер и т.д.) между подсистемами.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +  Container(NotificationService, "Notification Service", "Kotlin, Spring Boot", "Sends notifications and alerts")
См. постановку: Пользователь самостоятельно ... и просматривает телеметрию.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +
На стрелках, укажите протоколы и технологии взаимодействия (REST / Kafka protocol / Драйвер и т.д.) между контейнерами.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +  Container(DeviceManagement, "Device Management Service", "Kotlin, Spring Boot", "Manages device registration and configurations")
Очень схожие с ControlService контейнеры. Стоит подумать над объединением.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/ER/SmartHome_ER.puml
> +User ||--o| House : "Has"
Учесть, что несколько пользователей могут иметь доступ к одному дому, а один пользователь — к нескольким домам.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/ER/SmartHome_ER.puml
> +  +humidity: DECIMAL
Можем связать телеметрию с модулем. Значение телеметрии лучше хранить в одном числовом поле, а тип по типу модуля.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +System_Ext(HeatPumps, "Heat Pumps", "Smart heat pumps")
Объедините абстракцией - датчик, отправляет данные и состояние в Device Management Service.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +Rel(ControlService, Thermostats, "Controls thermostat devices")
Изменить направление связи. Настроить датчики на отправку сообщений в систему намного проще, чем "помнить" какие датчики запрашивать.

2024-11-20 19:40 UTC, dchekushin commented on sprint3/homework/README.md
> +Реализация в папке ./smart-home-monolith/diagrams/сomponents/SmartHomeMicroservices_Containers.puml
Диаграмма уровня компонентов детализирует внутреннюю структуру одного микросервиса, поправьте схему.

2024-11-21 13:25 UTC, vladis62 commented on sprint3/homework/README.md
> +Реализация в папке ./smart-home-monolith/diagrams/сomponents/SmartHomeMicroservices_Containers.puml
этот комментарий не понял, что именно поправить в схеме?

2024-11-22 15:50 UTC, dchekushin requested changes

2024-11-22 15:50 UTC, dchekushin commented on sprint3/homework/smart-home-monolith/diagrams/containers/SmartHomeMicroservices_Containers.puml
> +Rel(Sensor, Kafka, "Publishes telemetry and state updates", "MQTT")
Kafka к сожалению не может управлять устройствами. Не обладает соответствующими функциями. Устройства могут отправлять и получать данные в Device Management Service.

С помощью Kafka можем реализовать асинхронные взаимодействия, например, публиковать данные телеметрии.

2024-11-22 15:50 UTC, dchekushin commented on sprint3/homework/README.md
> +Реализация в папке ./smart-home-monolith/diagrams/сomponents/SmartHomeMicroservices_Containers.puml
Вопрос снят, сбило с толку название файла.

2024-11-25 17:44 UTC, merged